### ISSUE TITLE
How to use algorithms/PSO to generate data?

### ISSUE THREAD

**Issue by rodrigoclira** [macoj/swarm_interaction_network#5]
Hi Marcos,  I have a question.... 

Could you please tell me how to generate data for the framework ? It seems that you use the PSO available in algorithms/PSO but I haven't seen how to do that. Have you generated a jar file ? 

I would like to generate my own data files. 

![image](https://user-images.githubusercontent.com/276077/98192332-9c208900-1ef9-11eb-8fd1-b2e2eebc4a17.png)

Thanks for sharing this project.

**Comment by macoj** [comment]
Hi Rodrigo, thanks for the interest, and sorry for the delay. 

Yes, first you need to generate a .jar file using PSO/build.xml. Then, you can run the .jar:

```PSO.jar runs particles evaluations dimensions function topology mechanism [topology_parameter] [print_info] ```
These parameters are not really well documented currently, but you can find it here: https://github.com/macoj/swarm_interaction_network/blob/b5083970fb826a4a4362169338d99c510b31ce58/algorithms/PSO/src/pso/PSO.java#L142

The PSO.jar will simulate the PSO algorithm using the given parameters and spit out the instantaneous interaction graph at every iteration. You should pipe this to a file. This is the file used in the notebooks. 

Please let me know if you find have any issues.

Best wishes,
Marcos
